name: Nightly

on:
  schedule:
    # every night at midnight
    - cron:  '0 3 * * *'

jobs:

  instrumentation_tests:
    strategy:
      matrix:
        api-level: [21, 22, 23, 24, 25, 27, 28, 30]
      fail-fast: false
    runs-on: macOS-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: run instrumentation tests
        uses: ReactiveCircus/android-emulator-runner@v2.19.1
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          ndk: 21.4.7075529
          script: bash contrib/instrumentation_nightly.sh

      - name: Upload screenshot result
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ${{ matrix.api-level }}
          path: screencap.png

  unit_test_and_release:
    runs-on: ubuntu-18.04
    steps:

      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061" --sdk_root=${ANDROID_SDK_ROOT}

      - name: run unit tests
        run: ./gradlew testDebugUnitTest testCustomExampleDebugUnitTest

      - name: build debug
        run: ./gradlew assembleDebug

      - name: Decrypt files
        env:
          ssh_key: ${{ secrets.ssh_key }}
        run: |
          echo "$ssh_key" | base64 -d > ssh_key
          chmod 600 ssh_key

      - name: Set date variable
        run: echo "DATE=$(echo $(date +%Y-%m-%d))" >> $GITHUB_ENV

      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: app/build/outputs/apk/debug/*universal*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


